In [1]:
import pandas as pd
import numpy as np
import requests
import re

In [8]:
data = pd.read_csv("nfl_2021_stats.csv")

In [9]:
data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Games,Unnamed: 6,Receiving,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Total Yds,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Yds,...,1D,Lng,Y/A,Y/G,A/G,Touch,Y/Tch,YScm,RRTD,Fmb
1,1,Jonathan Taylor*+,IND,22,RB,17,17,51,40,360,...,107,83,5.5,106.5,19.5,372,5.8,2171,20,4
2,2,Cooper Kupp*+,LAR,28,WR,17,17,191,145,1947,...,1,18,4.5,1.1,0.2,149,13.2,1965,16,NaN
3,3,Deebo Samuel*+,SFO,25,WR,16,15,121,77,1405,...,21,49,6.2,22.8,3.7,136,13,1770,14,4
4,4,Najee Harris*,PIT,23,RB,17,17,94,74,467,...,62,37,3.9,70.6,18.1,381,4.4,1667,10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,Garrett Bradbury,MIN,26,C,13,13,1,1,21,...,0,NaN,NaN,NaN,NaN,1,21,21,0,NaN
496,496,Jesper Horsted,CHI,24,WR,7,0,3,2,21,...,0,NaN,NaN,NaN,NaN,2,10.5,21,2,NaN
497,497,Patrick Laird,MIA,26,RB,6,0,3,3,17,...,0,4,4,0.7,0.2,4,5.3,21,0,NaN
498,498,Gardner Minshew II,PHI,25,QB,4,2,NaN,NaN,NaN,...,2,9,2.3,5.3,2.3,9,2.3,21,0,1
499,499,Dezmon Patmon,IND,23,WR,8,0,4,2,21,...,0,NaN,NaN,NaN,NaN,2,10.5,21,1,NaN